[features]
seeds = false
skip-lint = false

[programs.devnet]
tweet_predict = "5pEnm6PoweBNFxjS8wTRUa63rn1ux8ab3ezsUjCV8UeR"

[programs.mainnet-beta]
tweet_predict = "5pEnm6PoweBNFxjS8wTRUa63rn1ux8ab3ezsUjCV8UeR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "target/deploy/tweet-predict-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/tweet-predict"]
